### ISSUE TITLE
Equipment Screenshot Not Taking

### ISSUE THREAD

**Issue by Shajeeb4** [Blackberry0Pie/equipment-screenshot#11]
Hi,

I have noticed an issue recently where the screenshot is not being taken. Tried both using right click method and button but no notifcation is coming up and nothing in clipboard either. My friend is having the same problem. Both of us have reinstalled it and still no luck.

Thanks

**Comment by DrJam** [comment]
also getting this issue, error from client.log
```
2024-11-05 09:10:00 GMT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at bbp.equipmentscreenshot.EquipmentScreenshotPlugin.paintEquipment(EquipmentScreenshotPlugin.java:586)
	at bbp.equipmentscreenshot.EquipmentScreenshotPlugin.screenshotEquipment(EquipmentScreenshotPlugin.java:808)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.pu(client.java:17797)
	at client.bc(client.java)
	at bz.ax(bz.java:394)
	at bz.id(bz.java)
	at bz.run(bz.java:4293)
	at java.base/java.lang.Thread.run(Unknown Source)
```
