### ISSUE TITLE
Plugin broken?

### ISSUE THREAD

**Issue by LarsinYousif** [Blackberry0Pie/equipment-screenshot#7]
I tried taking a screenshot using this plugin but it doesn't seem to be working.

Screenshot is not being saved in the screenshot folder and it's not going to my clipboard as configured.

**Comment by stev3nz** [comment]
I am experiencing the same issue. Haven't found a solution yet!

**Comment by LarsinYousif** [comment]
I get the following error in the client.log when attempting to use the plugin:

`2021-12-12 13:41:06 [Client] WARN  n.r.client.callback.ClientThread - Exception in invoke
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
	at bbp.equipmentscreenshot.EquipmentScreenshotPlugin.screenshotEquipment(EquipmentScreenshotPlugin.java:844)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:79)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:99)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:193)
	at client.ps(client.java:19568)
	at client.i(client.java)
	at am.u(am.java:335)
	at am.run(am.java:314)
	at java.base/java.lang.Thread.run(Unknown Source)
`

**Comment by LarsinYousif** [comment]
This appears to be caused by enabling the "Notify When Taken" option. Disabling the option fixes the issue.

**Comment by Blackberry0Pie** [comment]
oops
